pro10/pro10/pro10/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pro10_app.urls')),
]

pro10/pro10/pro10_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('register-student/', views.register_student, name='register_student'),
    path('register-course/', views.register_course, name='register_course'),
    path('student-list/<int:course_id>/', views.student_list, name='student_list'),
    path('projects_register/', views.register_project, name='register_project'),
    path('project_student_list/<int:project_id>/', views.project_student_list, name='project_student_list'),
    #path('student_detail/<int:stu_id>/', views.student_detail, name='student_detail'),

    path('students/', views.StudentListView.as_view(), name='student_list_all'),
    path('students/<int:pk>/', views.StudentDetailView.as_view(), name='student_detail'),
    
]

pro10/pro10/pro10_app/models.py
from django.db import models


class Course(models.Model):
  name = models.CharField(max_length=255)
  description = models.TextField(blank=True, null=True)
  def __str__(self):
    return self.name

class Project(models.Model):
  topic = models.CharField(max_length=100, default='')
  languages_used = models.CharField(max_length=100, default='')
  duration = models.IntegerField(default=0)
  def __str__(self):
    return self.topic

class Student(models.Model):
  first_name = models.CharField(max_length=255, default='')
  last_name = models.CharField(max_length=255, default='')
  email = models.EmailField(unique=True, default='')
  courses = models.ManyToManyField(Course, related_name='students', blank=True)
  projects = models.ManyToManyField(Project, related_name='students', blank=True)
  def __str__(self):
    return f"{self.first_name} {self.last_name}"
  

pro10/pro10/pro10_app/forms.py
from django import forms
from .models import Student, Course,Project

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'email', 'courses', 'projects']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'courses': forms.SelectMultiple(attrs={'class': 'form-select', 'data-toggle':'dropdown'}),
            'projects': forms.SelectMultiple(attrs={'class': 'form-select', 'data-toggle':'dropdown'}),
        }

class CourseForm(forms.ModelForm):
  class Meta:
    model = Course
    fields = ['name', 'description']
    widgets = {
      'name': forms.TextInput(attrs={'class': 'form-control'}),
      'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
    }

class ProjectForm(forms.ModelForm):
  class Meta:
    model = Project
    fields = ('topic', 'languages_used', 'duration')
    widgets = {
      'topic': forms.TextInput(attrs={'class': 'form-control'}),
      'languages_used': forms.TextInput(attrs={'class': 'form-control'}),
      'duration': forms.TextInput(attrs={'class': 'form-control'}),
      }

pro10/pro10/pro10_app/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Course,Project,Student
from .forms import StudentForm, CourseForm,ProjectForm
from django.views.generic import ListView, DetailView

def index(request):
  courses = Course.objects.all()
  projects = Project.objects.all()
  students = Student.objects.all()
  return render(request, 'index.html', {'courses': courses,'projects': projects,'students':students})

def register_student(request):
  if request.method == 'POST':
    form = StudentForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('index')
  else:
    form = StudentForm()
  return render(request, 'register_student.html', {'form': form})

def register_course(request):
  if request.method == 'POST':
    form = CourseForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('index')
  else:
    form = CourseForm()
  return render(request, 'register_course.html', {'form': form})

def student_list(request, course_id):
  course = Course.objects.get(id=course_id)
  students = course.students.all()
  return render(request, 'student_list.html', {'students': students, 'course': course})

def student_detail(request, stu_id):
    student = get_object_or_404(Student, id=stu_id)
    return render(request, 'student_detail.html', {'student': student})

def project_details(request, project_id):
  project = get_object_or_404(Project, pk = project_id)
  return render(request, 'project_details.html', {'project': project})

def project_student_list(request, project_id):
  project = Project.objects.get(id=project_id)
  students = project.students.all()
  return render(request, 'project_student_list.html', {'students': students, 'project': project})

def register_project(request):
  if request.method == 'POST':
    form = ProjectForm(request.POST)
    if form.is_valid():
      project = form.save()
      return redirect('index')
      #return redirect('project_detail', project_id=project.pk)
  else:
    form = ProjectForm()
  return render(request, 'register_project.html', {'form': form})



class StudentListView(ListView):
  model = Student
  template_name = 'stu_list.html'
  context_object_name = 'students'

class StudentDetailView(DetailView):
  model = Student
  template_name = 'student_detail.html'
  context_object_name = 'student'

pro10/pro10/pro10_app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Student Registration</title>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

pro10/pro10/pro10_app/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="container">

  <h1 class="mt-5">Courses</h1>
  <ul class="list-group mt-3">
    {% for course in courses %}
    <li class="list-group-item">
      <a href="{% url 'student_list' course.id %}">{{ course.name }}</a></li>
    {% endfor %}
  </ul>


  <h1>Projects</h1>
  <ul>
    {% for project in projects %}
    <li class="list-group-item">
      <a href="{% url 'project_student_list' project.id %}">{{ project.topic }}</a></li>
    {% endfor %}
  </ul>

  <h1 class="mt-5 my-5">Students</h1>
  <ul class="list-group mt-3">
    {% for student in students %}
    <li class="list-group-item">
      <a href="{% url 'student_detail' student.pk %}">{{ student.first_name }} {{student.last_name }}</a></li>
      {% endfor %}
  </ul>

  <a class="btn btn-primary mt-3" href="{% url 'register_student' %}">Register Student</a>
  <a class="btn btn-secondary mt-3" href="{% url 'register_course' %}">Register Course</a>
  <a class="btn btn-primary mt-3" href="{% url 'register_project' %}">Register Project</a>
</div>
{% endblock %}

pro10/pro10/pro10_app/templates/project_student_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Students Registered for {{ project.name }}</h1>
<ul>
    {% for student in students %}
        <li>{{ student.first_name }} {{ student.last_name }}</li>
    {% endfor %}
</ul>
{% endblock %}

pro10/pro10/pro10_app/templates/register_course.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Register Course</h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary text-center">Register</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

pro10/pro10/pro10_app/templates/register_project.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <h1>Create Project</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_topic">Topic:</label>
      {{ form.topic }}
    </div>
    <div class="form-group">
      <label for="id_languages_used">Languages Used:</label>
      {{ form.languages_used }}
    </div>
    <div class="form-group">
      <label for="id_duration">Duration:</label>
      {{ form.duration }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

pro10/pro10/pro10_app/templates/register_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Registration</title>
</head>
<body>
<div class="container">
    <h1>Register Student</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>
</body>
</html>

pro10/pro10/pro10_app/templates/stu_list.html
{% extends 'base.html' %} {% block content %}
<h1>Students</h1>
<ul>
  {% for student in students %}
  <li>
    <a href="{% url 'student_detail' student.pk %}"
      >{{ student.first_name }} {{ student.last_name }}</a
    >
  </li>
  {% endfor %}
</ul>
{% endblock %}

pro10/pro10/pro10_app/templates/student_detail.html
{% extends 'base.html' %} {% block content %}
<div class="container my-5">
    <h1>Name: {{ student.first_name }} {{ student.last_name }}</h1>
    <h1 class="card-title">Email: {{ student.email }}</h1>
</div>
{% endblock %}

pro10/pro10/pro10_app/templates/student_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Students Registered for {{ course.name }}</h1>
<ul>
    {% for student in students %}
        <li>{{ student.first_name }} {{ student.last_name }}</li>
    {% endfor %}
</ul>
{% endblock %}